---
# tasks file for role
- name: Inatsll webserver httpd
  yum:
    name={{ packname }}
    state=installed
  when: ansible_os_family == "RedHat"
- name: start webserver
  ansible.builtin.service:
    name={{ packname }}
    state=started
- name: Display script contents
  command: echo "Hello"
  register: command_out
- set_fact:
      command_output: "{{command_out.stdout_lines}}"
- name: msg
  debug:
    var: command_out.stdout_lines
- name: Copy index.html.j2
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
- name: Copy httpd.j2
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart webserver after every change
- name: create group deloitte
  ansible.builtin.group:
    name=deloitte
    state=present
- name: create user deploy
  ansible.builtin.user:
    name=deploy
    state=present
- name: install tools
  yum:
   name={{ item }}
   state=latest
  with_items:
    - git
    - ntp
    - vim
